-- CreateTable
CREATE TABLE `Admin` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user` VARCHAR(191) NOT NULL,
    `senha` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Admin_user_key`(`user`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Profissional` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `cpf` VARCHAR(191) NOT NULL,
    `senha` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `nome` VARCHAR(191) NOT NULL,
    `nascimento` DATETIME(3) NOT NULL,
    `matricula` VARCHAR(191) NOT NULL,
    `corencrm` VARCHAR(191) NOT NULL,
    `equipeVinculada` VARCHAR(191) NOT NULL,
    `centroSaudeVinculado` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Profissional_cpf_key`(`cpf`),
    UNIQUE INDEX `Profissional_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Patient` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(191) NOT NULL,
    `cpf` VARCHAR(191) NOT NULL,
    `cns` VARCHAR(191) NOT NULL,
    `nascimento` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `cep` VARCHAR(191) NOT NULL DEFAULT '',
    `endereco` VARCHAR(191) NOT NULL DEFAULT '',
    `numero` VARCHAR(191) NOT NULL DEFAULT '',
    `complemento` VARCHAR(191) NOT NULL DEFAULT '',
    `bairro` VARCHAR(191) NOT NULL DEFAULT '',
    `cidade` VARCHAR(191) NOT NULL DEFAULT '',
    `telefone` VARCHAR(191) NOT NULL DEFAULT '',
    `telefoneFamiliar` VARCHAR(191) NOT NULL DEFAULT '',
    `cor` VARCHAR(191) NOT NULL DEFAULT '',
    `estadoCivil` VARCHAR(191) NOT NULL DEFAULT '',
    `escolaridade` VARCHAR(191) NOT NULL DEFAULT '',
    `renda` VARCHAR(191) NOT NULL DEFAULT '',
    `profissao` VARCHAR(191) NOT NULL DEFAULT '',
    `equipeReferencia` VARCHAR(191) NOT NULL DEFAULT '',
    `centroSaudeReferencia` VARCHAR(191) NOT NULL DEFAULT '',
    `gestacoesAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    `partosNormaisAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    `partosCesarianasAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    `abortosAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    `dataUltimaGestacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `dataUltimaMenstruacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `diasMenstruada` VARCHAR(191) NOT NULL DEFAULT '',
    `intervaloEntreCiclosMenstruais` VARCHAR(191) NOT NULL DEFAULT '',
    `volumeMenstrual` VARCHAR(191) NOT NULL DEFAULT '',
    `colicas` VARCHAR(191) NOT NULL DEFAULT '',
    `contraceptivosAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    `contraceptivosAtuais` VARCHAR(191) NOT NULL DEFAULT '',
    `dataUltimoPreventivo` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ultimoPreventivoAlterado` VARCHAR(191) NOT NULL DEFAULT '',
    `possuiQualIst` VARCHAR(191) NOT NULL DEFAULT '',
    `fezQualCirurgiaPelvicaUterina` VARCHAR(191) NOT NULL DEFAULT '',
    `problemasSaude` VARCHAR(191) NOT NULL DEFAULT '',
    `medicacaoEmUso` VARCHAR(191) NOT NULL DEFAULT '',
    `alergiaCobreMedicamento` VARCHAR(191) NOT NULL DEFAULT '',
    `fezQualExameAlteracaoUtero` VARCHAR(191) NOT NULL DEFAULT '',
    `examesAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    `porqueInserirDIU` VARCHAR(191) NOT NULL DEFAULT '',
    `duvidasSobreInsercaoDIU` VARCHAR(191) NOT NULL DEFAULT '',
    `possuiTermoConsentimento` VARCHAR(191) NOT NULL DEFAULT '',
    `alturacm` VARCHAR(191) NOT NULL DEFAULT '',
    `pesokg` VARCHAR(191) NOT NULL DEFAULT '',
    `imc` VARCHAR(191) NOT NULL DEFAULT '',
    `realizouTesteGravidez` VARCHAR(191) NOT NULL DEFAULT '',
    `resultadoTesteGravidez` VARCHAR(191) NOT NULL DEFAULT '',
    `seSemTesteDeGravidezPorque` VARCHAR(191) NOT NULL DEFAULT '',
    `qualAlteracaoInspecaoGenital` VARCHAR(191) NOT NULL DEFAULT '',
    `qualAlteracaoExameEspecular` VARCHAR(191) NOT NULL DEFAULT '',
    `dataInsercao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `diuInserido` VARCHAR(191) NOT NULL DEFAULT '',
    `seDiuNaoInseridoPorque` VARCHAR(191) NOT NULL DEFAULT '',
    `usoPrevioAINE` VARCHAR(191) NOT NULL DEFAULT '',
    `antissepsiaRealizadaCom` VARCHAR(191) NOT NULL DEFAULT '',
    `histerometriaCm` VARCHAR(191) NOT NULL DEFAULT '',
    `tamanhoFioCm` VARCHAR(191) NOT NULL DEFAULT '',
    `modeloDiu` VARCHAR(191) NOT NULL DEFAULT '',
    `loteDiu` VARCHAR(191) NOT NULL DEFAULT '',
    `intercorrenciasDiu` VARCHAR(191) NOT NULL DEFAULT '',
    `nivelDor` VARCHAR(191) NOT NULL DEFAULT '',
    `profissionalInseriuNome` VARCHAR(191) NOT NULL DEFAULT '',
    `profissionalInseriuCRMCoren` VARCHAR(191) NOT NULL DEFAULT '',
    `centroSaudeInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `auxilioSegundoProfissional` VARCHAR(191) NOT NULL DEFAULT '',
    `profissionalAuxiliarNome` VARCHAR(191) NOT NULL DEFAULT '',
    `profissionalAuxiliarCRMCoren` VARCHAR(191) NOT NULL DEFAULT '',
    `dataAcompanhamento` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `diasSangramentoPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `nivelSatisfacaoInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `dataUltimaMenstruacaoPosInsercao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `diasMenstruadaPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `intervaloDiasUltimoCicloPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `volumeMenstrualPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `colicasPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `tamanhoFioCmPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `resultadoUSG` VARCHAR(191) NOT NULL DEFAULT '',
    `intercorrenciasComunicadasPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `qualOutraIntercorrenciaPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    `dataRemocaoDIU` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `motivoRemocaoDIU` VARCHAR(191) NOT NULL DEFAULT '',
    `prescricaoOutroContraceptivo` VARCHAR(191) NOT NULL DEFAULT '',
    `seraInseridoNovoDIU` VARCHAR(191) NOT NULL DEFAULT '',

    UNIQUE INDEX `Patient_cpf_key`(`cpf`),
    UNIQUE INDEX `Patient_cns_key`(`cns`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
