/*
  Warnings:

  - You are about to alter the column `possuiTermoConsentimento` on the `patient` table. The data in that column could be lost. The data in that column will be cast from `TinyInt` to `VarChar(191)`.

*/
-- AlterTable
ALTER TABLE `patient` MODIFY `cep` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `endereco` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `numero` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `complemento` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `bairro` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `cidade` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `telefone` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `telefoneFamiliar` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `cor` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `estadoCivil` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `escolaridade` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `renda` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `profissao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `equipeReferencia` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `centroSaudeReferencia` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `gestacoesAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `partosNormaisAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `partosCesarianasAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `abortosAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `diasMenstruada` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `intervaloEntreCiclosMenstruais` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `volumeMenstrual` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `colicas` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `contraceptivosAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `contraceptivosAtuais` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `ultimoPreventivoAlterado` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `possuiQualIst` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `fezQualCirurgiaPelvicaUterina` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `problemasSaude` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `medicacaoEmUso` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `alergiaCobreMedicamento` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `fezQualExameAlteracaoUtero` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `examesAnteriores` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `porqueInserirDIU` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `duvidasSobreInsercaoDIU` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `possuiTermoConsentimento` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `alturacm` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `pesokg` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `imc` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `realizouTesteGravidez` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `resultadoTesteGravidez` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `seSemTesteDeGravidezPorque` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `qualAlteracaoInspecaoGenital` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `qualAlteracaoExameEspecular` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `diuInserido` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `seDiuNaoInseridoPorque` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `usoPrevioAINE` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `antissepsiaRealizadaCom` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `histerometriaCm` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `tamanhoFioCm` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `modeloDiu` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `loteDiu` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `intercorrenciasDiu` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `nivelDor` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `profissionalInseriuNome` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `profissionalInseriuCRMCoren` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `centroSaudeInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `auxilioSegundoProfissional` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `profissionalAuxiliarNome` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `profissionalAuxiliarCRMCoren` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `diasSangramentoPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `nivelSatisfacaoInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `diasMenstruadaPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `intervaloDiasUltimoCicloPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `volumeMenstrualPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `colicasPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `tamanhoFioCmPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `resultadoUSG` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `intercorrenciasComunicadasPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `qualOutraIntercorrenciaPosInsercao` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `motivoRemocaoDIU` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `prescricaoOutroContraceptivo` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `seraInseridoNovoDIU` VARCHAR(191) NOT NULL DEFAULT '';
